export const categories = [
  "Almacen",
  "Alquiler",
  "Auto",
  "Carniceria",
  "Cecilia varios",
  "Elizabeth varios",
  "Farmacia",
  "Fernando varios",
  "Garage",
  "Jardin",
  "Nafta",
  "Netflix",
  "Panaderia",
  "Patente",
  "Peajes",
  "Personal Flow",
  "Regalos",
  "Remis",
  "Saldo Inicial",
  "Sueldo",
  "Salidas",
  "Servicio Luz",
  "Servicio Gas",
  "Tarjetas",
  "Verduleria",
];
